### ISSUE TITLE
Compatibility with More Hotbar Slots mod

### ISSUE THREAD

**Issue by SpiritAxolotl** [CertifiedPyro/InventoryTweaks#1]
Simple request for the keys 6-0 to work when these two mods are installed

mod link: https://thunderstore.io/c/webfishing/p/CopyKatt/More_Hotbar_Slots/

**Comment by CertifiedPyro** [comment]
Could you elaborate a little more? The "More Hotbar Slots" mod works for me with Inventory Tweaks installed, and I'm able to assign items to keys 6-0.

**Comment by SpiritAxolotl** [comment]
Oh my mistake. I must have not had anything in my hotbar when I tried it. Sorry!!
